@Ordering.Api_HostAddress = http://localhost:5076

POST {{Ordering.Api_HostAddress}}/orders/
Content-Type: application/json

{
  "customerName": "uat",
  "productId": "acecf5f3-ec38-447c-a5a9-44cc7e8c9e1a",
  "quantity": 4
}

###
